[package]
name = "typst-lt"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
annotate-snippets = "0.9.1"
clap = "4.3.21"
dashmap = "5.5.3"
languagetool-rust = "2.1.4"
notify = "6.0.1"
notify-debouncer-mini = "0.3.0"
serde = "1.0.183"
serde_json = "1.0.104"
substring = "1.4.5"
tokio = { version = "1.30.0", features = ["io-std"] }
tower-lsp = "0.20.0"
typst-syntax = { git = "https://github.com/typst/typst.git" }
